version: 2
updates:
  - package-ecosystem: pip
    labels:
      - dependencies
    directories:
      - backend/
      - client/python/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    labels:
      - dependencies
    directories:
      - backend/
      - /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    labels:
      - CI/CD
      - dependencies
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    labels:
      - dependencies
    directory: /client/typescript/
    schedule:
      interval: weekly
