apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
namespace: spellbook-dev
images:
  - name: 083767677168.dkr.ecr.us-east-2.amazonaws.com/spellbook-client-prod-ecr
    newName: 083767677168.dkr.ecr.us-east-2.amazonaws.com/spellbook-client-dev-ecr
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/resources/requests/cpu"
        value: "100m"
    target:
      kind: Deployment
      name: spellbook-client

  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/resources/requests/memory"
        value: "256M"
    target:
      kind: Deployment
      name: spellbook-client
